In [1]:
import numpy as np

# 차원 변경

## 배열을 합치기

In [2]:
np.hstack([[10, 20], [100, 200]])

array([ 10,  20, 100, 200])

In [3]:
np.vstack([[10, 20], [100, 200]])

array([[ 10,  20],
       [100, 200]])

In [4]:
np.hstack([[[10, 20], [30, 40]], [[100, 200], [300, 400]]])

array([[ 10,  20, 100, 200],
       [ 30,  40, 300, 400]])

In [5]:
np.stack([[10, 20], [30, 40]], axis=0)

array([[10, 20],
       [30, 40]])

In [7]:
np.stack([[10, 20], [30, 40]], axis=1)

array([[10, 30],
       [20, 40]])

In [8]:
np.stack([[[10, 20], [30, 40]], [[100, 200], [300, 400]]], axis=0)

array([[[ 10,  20],
        [ 30,  40]],

       [[100, 200],
        [300, 400]]])

In [9]:
np.stack([[[10, 20], [30, 40]], [[100, 200], [300, 400]]], axis=1)

array([[[ 10,  20],
        [100, 200]],

       [[ 30,  40],
        [300, 400]]])

In [10]:
np.stack([[[10, 20], [30, 40]], [[100, 200], [300, 400]]], axis=2)

array([[[ 10, 100],
        [ 20, 200]],

       [[ 30, 300],
        [ 40, 400]]])

In [12]:
np.concatenate([[1,2], [2, 3], [4,5]])

array([1, 2, 2, 3, 4, 5])

In [13]:
# np.concatenate([[A, B], [C, D]], axis=0) => [A, B, C, D]
# [[1, 2], [3, 4]] + [[5, 6], [7, 8]]
np.concatenate([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
# [[1, 2] + [5, 6], [3, 4]+[7, 8]]
np.concatenate([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [15]:
np.append([1, 2, 3], [4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [16]:
my_array = [1, 2, 3]
my_array.append([4, 5, 6])
my_array

[1, 2, 3, [4, 5, 6]]

In [17]:
my_array = [1, 2, 3]
my_array.extend([4, 5, 6])
my_array

[1, 2, 3, 4, 5, 6]

In [18]:
my_array = np.ones((2, 3, 4))
my_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
np.reshape(my_array, (12, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
my_array.reshape(12, 2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
my_array.reshape(12, -1) # 12 * x = 24

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
my_array.reshape(-1, 2) # x * 2 = 24

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
my_array.reshape(4, -1, 2)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [24]:
my_array.reshape(4, 3, -1)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [25]:
my_array.reshape(-1, 3, 2)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [26]:
my_array.reshape(24)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [27]:
my_array.reshape(-1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [28]:
my_array.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.array(my_array.flat)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [31]:
my_array.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [32]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
my_array.reshape(2, 3, -1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [34]:
my_array.reshape(2, 3, -1).shape

(2, 3, 1)

In [35]:
my_array.reshape(-1, 2, 3)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [36]:
my_array.reshape(-1, 2, 3).shape

(1, 2, 3)

In [37]:
np.expand_dims(my_array, 0)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [38]:
np.expand_dims(my_array, 1)

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [39]:
np.expand_dims(my_array, 2)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [40]:
my_array = np.arange(36)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [41]:
my_array.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [42]:
my_array.reshape(2, 3, -1)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [43]:
my_array.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [46]:
my_array.reshape(2, 2, -1)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]]])

In [ ]:
[[[[1, 2], [2, 4]], [[2, 3], [4, 2]]], [[[1, 2], [2, 4]], [[2, 3], [4, 2]]]]